version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/codepipeline  # Change this to the actual directory where your Symfony app will be deployed

hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
      script: |
        chmod +x /var/www/codepipeline/scripts/install_dependencies.sh  # Ensure the script is executable
    - location: scripts/clear_cache.sh
      timeout: 300
      runas: root
    - location: scripts/set_permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: clear_apcu_cache.sh
      timeout: 300
      runas: root
      script: |
          chmod +x /var/www/codepipeline/scripts/clear_apcu_cache.sh  # Ensure the script is executable
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: scripts/validate.sh
      timeout: 300
      runas: root
