version: 0.2

env:
  variables:
    APP_ENV: prod # You can change this based on your environment
    SYMFONY_ENV: prod
  shell: bash

phases:
  install:
    commands:
      - echo Installing PHP and Composer
      - yum install -y amazon-linux-extras
      - amazon-linux-extras enable php8.1
      - yum clean metadata
      - yum install -y php php-cli php-json php-mbstring php-xml php-zip
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - echo Installing project dependencies
      - composer install --no-interaction --prefer-dist --optimize-autoloader

  pre_build:
    commands:
      - echo Running Symfony cache:clear
      - php bin/console cache:clear --env=${APP_ENV}
      - echo Running Symfony cache:warmup
      - php bin/console cache:warmup --env=${APP_ENV}

  build:
    commands:
      - echo Running database migrations
      - php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration

  post_build:
    commands:
      - echo Symfony build completed

artifacts:
  files:
    - vendor/**
    - public/**
    - var/**
    - config/**
    - .env
    - composer.json
    - composer.lock
  discard-paths: no

cache:
  paths:
    - vendor/**/*
    - var/cache/**/*