version: 0.2

phases:
  install:
    commands:
      - echo Installing Composer
      - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
      - echo Installing project dependencies
      - composer install --no-interaction --prefer-dist --optimize-autoloader

  pre_build:
    commands:
      - echo Running Symfony cache:clear
      - php bin/console cache:clear --env=prod
      - echo Running Symfony cache:warmup
      - php bin/console cache:warmup --env=prod

  build:
    commands:
      - echo Running database migrations

  post_build:
    commands:
      - echo Symfony build completed

artifacts:
  files:
    - bin/**
    - config/**
    - script/**
    - src/**
    - vendor/**
    - public/**
    - var/**
    - config/**
    - .env
    - composer.json
    - composer.lock
  discard-paths: no

cache:
  paths:
    - vendor/**/*
    - var/cache/**/*